### PR TITLE
First preparations for event calling

### PR DESCRIPTION
**Pull request by yannicklamprecht**
Implements Event calling.

# TODOS:

- [x] Wrap Subscriber to allow post actions events
- [ ] Call pre action events and handle cancel status

### CODE REVIEW

**Comment by yannicklamprecht** [comment]
A lot of events aren't defined yet, so it's in a blocked state.

Probably Missing Events?!:

- [ ] AccountNameChangeEvent
- [ ] AccountNameChangedEvent
- [ ] AccountRetrieveBalanceEvent
- [ ] AccountRetrievedBalanceEvent
- [ ] AccountBalanceModifyEvent
- [ ] AccountBalanceModifiedEvent
- [ ] AccountDoTransactionEvent
- [ ] AccountDidTransactionEvent
- [ ] AccountDeleteEvent
- [ ] AccountDeletedEvent
- [ ] AccountHistoryRetrieveEvent
- [ ] AccountHistoryRetrievedEvent
- [ ] AccountMemberIdsRetrievedEvent
- [ ] AccountIsMemberEvent
- [ ] AccountModifyPermissionEvent
- [ ] AccountModifiedPermissionEvent
- [ ] AccountPermissionsRetrieveEvent
- [ ] AccountPermissionsRetrievedEvent
- [ ] AccountPermissionCheckEvent
- [ ] AccountPermissionCheckedEvent

- [ ] PlayerAccountBalanceResetEvent

**Comment by lokka30** [comment]
Thank you very much! I have a few questions:

- Are you sure this PR is no longer a draft?
- How is the EventEconomyProvider utilized? I don't see any entry points for it.

And here are my opinions on each event you listed above:

<details>
<summary>[View Opinions...]</summary>

- I would prefer using the word `Update` than `Change` and `Modify` in the event names.
- Unsure if I prefer present/post-tense words (e.g. `do-transaction` and `did-transaction`) or using prefixes like `Pre` and `Post` (e.g. `pre-transaction` and `post-transaction`).
- I'm unsure about any of these events being modifiable / cancellable. It could break plugins by cancelling them or changing their state.

Yes:
- `AccountBalanceModifyEvent`
- `AccountBalanceModifiedEvent`
- `AccountDoTransactionEvent`
- `AccountDidTransactionEvent`
- `AccountDeleteEvent`
- `AccountDeletedEvent`
- `AccountModifyPermissionEvent`
- `AccountModifiedPermissionEvent`

Maybe:
- `AccountNameChangeEvent`
- `AccountNameChangedEvent`
- `AccountRetrieveBalanceEvent`
- `AccountRetrievedBalanceEvent`
- `AccountHistoryRetrieveEvent`
- `AccountHistoryRetrievedEvent`
- `AccountMemberIdsRetrievedEvent`
- `AccountIsMemberEvent`
- `AccountAddMemberEvent` and `AccountRemoveMemberEvent`
    - added these two to the list, thought they were missing from the original
- `AccountPermissionsRetrieveEvent`
- `AccountPermissionsRetrievedEvent`

Probably no:
- `PlayerAccountBalanceResetEvent`
- `AccountPermissionCheckEvent`
- `AccountPermissionCheckedEvent`

</details>

**Comment by MrIvanPlays** [comment]
as i see it, this api you will introduce will be a wrapper of the implemented api by economy providers, am i right? if i am, i don't really like this approach, but if others are agreeing i won't stop from merging.

**Comment by lokka30** [comment]
> as i see it, this api you will introduce will be a wrapper of the implemented api by economy providers, am i right? if i am, i don't really like this approach, but if others are agreeing i won't stop from merging.

I have the same opinion if such is the case.

**Comment by yannicklamprecht** [comment]
Feel free to close. 👍🏼 Yeah it's a wrapper.
The alternative could be the Template Pattern. https://www.tutorialspoint.com/design_pattern/template_pattern.htm

**Comment by lokka30** [comment]
> Feel free to close. 👍🏼 Yeah it's a wrapper. The alternative could be the Template Pattern. https://www.tutorialspoint.com/design_pattern/template_pattern.htm

The template pattern sounds like a brilliant alternative! @MrIvanPlays do you think that route would be viable for this?

**Comment by MrIvanPlays** [comment]
that's gonna rock the boat too much. in which way we are obliged to call them? fgs they're only 2 events to call! the economy provider can do this easily.

**Comment by lokka30** [comment]
> that's gonna rock the boat too much. in which way we are obliged to call them? fgs they're only 2 events to call! the economy provider can do this easily.

Although I don't think it is at all *necessary*, if we do go with the template pattern then we can add several other events (see my original reply with the events list in a dropdown).

However I am currently more orientated to keep things the way it is.

**Comment by lokka30** [comment]
Regardless of the PR being closed I am very grateful for your contribution @yannicklamprecht. Thank you very much. :)

**Pull request closed without merging**
