### PR TITLE
Deprecation and eventual removal of API Versions

### PR DESCRIPTION
**Pull request by lokka30**
I would also like to discuss a target plugin version for the complete removal of all associated classes and methods. :)

I think removing it in v1.2.0 could leave a damaged (albeit little to none) reputation of the library's stability. Perhaps v1.3.0?

### CODE REVIEW

**Comment by MrIvanPlays** [comment]
we will remove deprecated stuff in 2.0 in order to follow semver.

**Review by MrIvanPlays — APPROVED** [review]

**Comment by MrIvanPlays** [comment]
> We could give a 5 minor updates time frame to remove deprecated APIs or with every major remove everything that's deprecated although the last option may not give much time to adapt in certain scenarios

im fairly sure we're releasing 1.1 and we're gonna stop the development for a bit ; start helping people to implement treasury support

**Comment by lokka30** [comment]
> > We could give a 5 minor updates time frame to remove deprecated APIs or with every major remove everything that's deprecated although the last option may not give much time to adapt in certain scenarios
> 
> im fairly sure we're releasing 1.1 and we're gonna stop the development for a bit ; start helping people to implement treasury support

^^^ this.

so to remove deprecated stuff, the following factors are at play:
* how many people are using the deprecated code
* how long it has been since the code was marked as deprecated
* how urgent we are to remove the deprecated code

for the API version removal, these are the factors:
* few plugins are using the deprecated code
* code was only marked as deprecated just now so we should wait either a major version or a month or so.
* not urgent since it does not affect anything by using it

**Comment by MrNemo64** [comment]
Sounds about right

**Review by Jikoo — APPROVED** [review]
Agree that per semver the deprecated methods should not be removed until 2.0, but there's no reason to not release a 2.0 even if it's exclusively to remove deprecated methods after a sufficient wait.

**Pull request merged**
