### PR TITLE
Javadocs

### LINKED ISSUE #4: Add missing javadocs
This is currently being worked on by @MrIvanPlays and I.

- [x] fix formatting of existing javadocs
- [x] add missing javadocs

### LINKED ISSUE #27: Fix JavaDoc formatting
Currently the Javadoc format follows a pattern: author - see - since - description - parameters - throws - return
This format creates the problem that JavaDoc genertors think that the description is part of the see tag, we can see this by generating the javadoc.
Image of generated JavaDoc
Another problem with it is using formatting options that don't exists in the JavaDoc like \`Marked` This JavaDoc was generated using the java 8 jdk

### LINKED ISSUE #46: Changes to the EconomyAPIVersion
Right now the EconomyAPIVersion class is really simple: Identifyes mayor versions with a number, not more not less. I think this should change. I propose some changes

1. Change the use of the `@since` tag, instead of `@since v1.0.0` we could use `@since {@link me.lokka30.treasury.api.economy.misc.EconomyAPIVersion#VERSION_1 v1.0.0}` in the documentation shows the same but it provides a link to the enum version
2. Change enum entryes naming, instead of `VERSION_1` we could use `v1_0_0` 
3. Specify an order. All enums implement the `Comparable<>` interface with the default logic being indexes. Since this logic doesn't necesarily apply to us it would make sense to specify out comparing logic
4. Change the number system. Using integers to know what version it is means that we can only represent big updates, we could have an array of ints/shorts/bytes (probably shorts is enough for all versions we may release)
5. (Optional) in de documentation of each entry list the changes of that version

I can make a class with this features so you see what I mean

### PR DESCRIPTION
**Pull request by MrIvanPlays**
Intends to close #4 
Intends to close #27 
~~Intends to close 46~~ ~~will be done in another PR~~

~~Currently blocked via 49~~ ~~blocked until api versioning changes get merged~~ waiting on #53 since it does some javadoc changes. then this will get updated

Any suggestions appreciated.

### CODE REVIEW

**Review by lokka30 — APPROVED** [review]

**Comment by lokka30** [comment]
Thanks! Ready to be merged?

**Comment by MrIvanPlays** [comment]
No.

**Comment by lokka30** [comment]
Once I've completed #55, I'll help out with this PR.

**Comment by lokka30** [comment]
What happened in https://github.com/lokka30/Treasury/pull/50/commits/e9645bc7598164953d7a0b9c487b0494a4211649 ?

**Comment by MrIvanPlays** [comment]
> What happened in [e9645bc](https://github.com/lokka30/Treasury/commit/e9645bc7598164953d7a0b9c487b0494a4211649) ?

I have 0 idea. Something when merging the branches and this commit: https://github.com/lokka30/Treasury/commit/81ca0ca6d7ad58a62cfd779cfb2c0b454a2e1fc8

**Comment by MrIvanPlays** [comment]
will recreate since this branch got messed up

**Pull request closed without merging**
